#!/bin/sh
set -e

lb config noauto \
    --distribution "resolute" \
    --archive-areas "main restricted universe multiverse" \
    --binary-images iso-hybrid \
    --architecture amd64 \
    --linux-flavours generic \
    --bootloader grub-efi \
    --source false \
    --memtest none \
    --compression xz \
    --iso-application "Linux-Universe" \
    --iso-volume "Linux-Universe" \
    --iso-publisher "Linux-Universe-Project" \
    "${@}"
