extraMounts:
    - device: none
      fs: "btrfs"
      mountPoint: "/"
      options: "subvol=@,compress=zstd,noatime"

    - device: none
      fs: "btrfs"
      mountPoint: "/home"
      options: "subvol=@home,compress=zstd,noatime"

    - device: none
      fs: "btrfs"
      mountPoint: "/var"
      options: "subvol=@var,compress=zstd,noatime"

    - device: none
      fs: "btrfs"
      mountPoint: "/.snapshots"
      options: "subvol=@snapshots,compress=zstd,noatime"
