efi:
    systemPartition: "/boot/efi"
    uuid: false

userSwapChoices:
    - none
    - small

drawNestedPartitions: true
alwaysShowPartitionLabels: true

defaultFileSystemType: "btrfs"

availableFileSystemTypes: ["btrfs", "ext4"]

btrfsSubvolumes:
    - mountPoint: "/"
      subvolume: "@"
    - mountPoint: "/home"
      subvolume: "@home"
    - mountPoint: "/var"
      subvolume: "@var"
    - mountPoint: "/.snapshots"
      subvolume: "@snapshots"

initialPartitioningChoice: erase
initialSwapChoice: none

neverCreateSwap: false
enableLuksAutomatedPartitioning: true

customPartitionMode: normal
